services:
  nginx:
    container_name: nginx-proxy
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
      - backend3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 10
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  backend1:
    #image: nginx:alpine
    container_name: backend1
    build:
      context: ./src
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    environment:
      - DO_ENDPOINT_MAX_LATENCY=500
    ports:
      - 8081:80
    networks:
      - app_network
    cap_add:
      - NET_ADMIN

  backend2:
    #image: nginx:alpine
    container_name: backend2
    build:
      context: ./src
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    ports:
      - 8082:80
    networks:
      - app_network
    cap_add:
      - NET_ADMIN

  backend3:
    #image: nginx:alpine
    container_name: backend3
    build:
      context: ./src
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    ports:
      - 8083:80
    networks:
      - app_network
    cap_add:
      - NET_ADMIN

  k6:
    image: grafana/k6:latest
    volumes:
      - ./k6_scripts:/scripts
    networks:
      - app_network

networks:
  app_network:
    name: app_network
    driver: bridge
